### ISSUE TITLE
1.0.6 error opening options for the first time (dependency needed?)

### ISSUE THREAD

**Issue by ceylina** [Benio101/Aye.PullTime#1]
With only aye and aye.pulltime installed, the following error happens when you initially open the interface options for the first time

However, having the aye.warnings does not throw this error so does this mean that aye.warnings is a dependency of aye.pulltime?

Aye.PullTime\Aye.PullTime.options.lua:569: attempt to index field 'Warnings' (a nil value)
Aye.PullTime\Aye.PullTime.options.lua:569: in function `member'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-61.lua:249: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:197>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-61.lua:1169: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1055>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-61.lua:1588: in function `FeedGroup'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-61.lua:1513: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1493>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?
Aye\libs/AceGUI-3.0\AceGUI-3.0-34.lua:314: in function `Fire'
...ibs/AceGUI-3.0-34\widgets\AceGUIContainer-TreeGroup.lua:523: in function `Select'
...ibs/AceGUI-3.0-34\widgets\AceGUIContainer-TreeGroup.lua:531: in function `SelectByValue'
...
(tail call): ?
[C]: ?
[string "safecall Dispatcher[2]"]:9: in function <[string "safecall Dispatcher[2]"]:5>
(tail call): ?
Aye\libs/AceGUI-3.0\AceGUI-3.0-34.lua:314: in function `Fire'
...GUI-3.0\widgets\AceGUIContainer-BlizOptionsGroup.lua:20: in function <...GUI-3.0\widgets\AceGUIContainer-BlizOptionsGroup.lua:19>
[C]: in function `Show'
FrameXML\InterfaceOptionsFrame.lua:28: in function `InterfaceOptionsList_DisplayPanel'
FrameXML\InterfaceOptionsFrame.lua:46: in function `InterfaceOptionsListButton_OnClick'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>

**Comment by Benio101** [comment]
Hello, this happened due to typo in commit #[`a3349c97564a6c46cc00ac5f5263dabd12bd1e6f`](https://github.com/Benio101/Aye.PullTime/commit/a3349c97564a6c46cc00ac5f5263dabd12bd1e6f).
No, `Aye.PullTime` should not require `Aye.Warnings` as dependency, this was done due to typo.

I will push fix within a few minutes.
Sorry for inconviencence.

Kee

**Comment by Benio101** [comment]
Fixed version `1.0.7` is available to download directly from github live: [https://github.com/Benio101/Aye.PullTime/releases/tag/1.0.7](https://github.com/Benio101/Aye.PullTime/releases/tag/1.0.7) and from curse once approved by moderator: [https://mods.curse.com/addons/wow/ayepulltime](https://mods.curse.com/addons/wow/ayepulltime).
